services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
# Commenting this out for test purposes
#    volumes:
#      - ./data/postgres_db:/var/lib/postgresql/data